name: find_my_pet
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.3.8
  pinput: ^3.0.1
  qr_scanner_overlay: ^0.0.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  firebase_auth: ^4.15.1
  firebase_core: ^2.24.1
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.4
  dio: ^5.4.0
  intl: ^0.19.0
  lottie: ^2.7.0
  collection: ^1.18.0
  fluttertoast: ^8.2.4
  get:
  camera: ^0.10.5+6
  google_maps_flutter: ^2.5.0
  animated_text_kit: ^4.2.2
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icons/
    - assets/app_images/
    - assets/animations/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
  fonts:
    enabled: true
flutter_native_splash:
  background_image: assets/animations/splash.gif
  android_12:
    color: "#ffffff"
    image: assets/animations/splash.gif

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_images/app_icon.png"
  remove_alpha_ios: true
  image_path_ios: "assets/app_images/app_icon.png"
  ios: true
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/app_images/app_icon.png"
